services:
  - type: web
    name: sentinelai-backend
    runtime: docker
    region: oregon
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: MONGODB_URL
        sync: false
      - key: MONGODB_DB_NAME
        value: sentinelai
      - key: ALLOWED_ORIGINS
        sync: false
