from io import BytesIO
from datetime import datetime

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from pymongo.database import Database
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
from reportlab.lib.styles import getSampleStyleSheet

from app.core.database import get_db

router = APIRouter()

@router.get("/executive-pdf")
async def generate_executive_pdf(
    db: Database = Depends(get_db),
):

    malware_count = db["scans"].count_documents(
        {
            "scan_type": "malware",
            "verdict": {
                "$in": [
                    "Malicious",
                    "Suspicious"
                ]
            }
        }
    )

    phishing_count = db["scans"].count_documents(
        {
            "scan_type": "phishing"
        }
    )

    critical_cves = db["cve_records"].count_documents(
        {
            "severity": "Critical"
        }
    )

    attack_chains = 1 if (
        malware_count > 0 and
        phishing_count > 0 and
        critical_cves > 0
    ) else 0

    alerts_total = db["alerts"].count_documents({})
    open_alerts = db["alerts"].count_documents(
        {"status": "Open"}
    )

    risk_score = min(
        100,
        malware_count * 3 +
        phishing_count * 5 +
        critical_cves * 2
    )

    if risk_score >= 90:
        grade = "F"
    elif risk_score >= 75:
        grade = "D"
    elif risk_score >= 60:
        grade = "C"
    elif risk_score >= 40:
        grade = "B"
    else:
        grade = "A"

    top_cves = list(
        db["cve_records"]
        .find()
        .sort("risk_score", -1)
        .limit(10)
    )

    recent_alerts = list(
        db["alerts"]
        .find()
        .sort("created_at", -1)
        .limit(10)
    )

    total_alerts = db["alerts"].count_documents({})

    critical_alerts = db["alerts"].count_documents(
        {"severity": "Critical"}
    )

    high_alerts = db["alerts"].count_documents(
        {"severity": "High"}
    )

    open_alerts = db["alerts"].count_documents(
        {"status": "Open"}
    )

    recent_malware = list(
        db["scans"]
        .find(
            {"scan_type": "malware"}
        )
        .sort("created_at", -1)
        .limit(10)
    )

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph(
            "SentinelAI Executive Security Assessment",
            styles["Title"]
        )
    )
    content.append(
        Paragraph(
            "Autonomous Cyber Defense Platform",
            styles["Heading3"]
        )
    )
    content.append(
        Paragraph(
            f"Generated by SentinelAI SOC Engine",
            styles["Italic"]
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            f"Generated: {datetime.utcnow()}",
            styles["Normal"]
        )
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Executive Summary",
            styles["Heading1"]
        )
    )

    summary_table = Table(
        [
            ["Metric", "Value"],
            ["Security Grade", grade],
            ["Risk Score", str(risk_score)],
            ["Malware Detections", str(malware_count)],
            ["Phishing Events", str(phishing_count)],
            ["Critical CVEs", str(critical_cves)],
            ["Open Alerts", str(open_alerts)],
            ["Attack Chains", str(attack_chains)],
        ]
    )

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.darkblue),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ])
    )
    assessment = f"""
    Current security posture is classified as HIGH RISK.
    The environment contains {critical_cves} critical
    vulnerabilities, {malware_count} malware detections,
    and {open_alerts} active alerts requiring investigation.
    """
    content.append(
        Paragraph(
            assessment,
            styles["BodyText"]
        )
    )

    content.append(summary_table)

    content.append(PageBreak())

    content.append(
        Paragraph(
            "Vulnerability Intelligence",
            styles["Heading1"]
        )
    )

    cve_data = [
        ["CVE", "Severity", "Risk"]
    ]

    for cve in top_cves:
        cve_data.append([
            cve.get("cve_id", "N/A"),
            cve.get("severity", "Unknown"),
            str(cve.get("risk_score", 0))
        ])

    cve_table = Table(cve_data)

    cve_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.darkred),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
        ])
    )

    content.append(cve_table)
    content.append(PageBreak())

    content.append(
        Paragraph(
            "Malware Analysis",
            styles["Heading1"]
        )
    )

    malware_data = [
        ["File", "Verdict", "Threat"]
    ]

    for scan in recent_malware:

        malware_data.append([
            scan.get("file_name", "Unknown"),
            scan.get("verdict", "Unknown"),
            scan.get("threat_level", "Unknown")
        ])

    malware_table = Table(malware_data)

    malware_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.darkgreen),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
        ])
    )

    content.append(malware_table)

    content.append(PageBreak())

    content.append(
        Paragraph(
            "Alert Analysis",
            styles["Heading1"]
        )
    )

    alert_summary_data = [
        ["Metric", "Count"],
        ["Total Alerts", str(total_alerts)],
        ["Critical Alerts", str(critical_alerts)],
        ["High Alerts", str(high_alerts)],
        ["Open Alerts", str(open_alerts)],
    ]

    alert_summary_table = Table(
        alert_summary_data,
        colWidths=[250, 100]
    )

    alert_summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.darkblue),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ])
    )

    content.append(alert_summary_table)

    content.append(Spacer(1, 20))
    content.append(
        Paragraph(
            "Recent Alerts",
            styles["Heading2"]
        )
    )

    alert_data = [
        ["Severity", "Title", "Status"]
    ]
    for alert in recent_alerts:

        alert_data.append([
            alert.get("severity", "Unknown"),
            alert.get("title", "Unknown"),
            alert.get("status", "Unknown"),
        ])

    alert_table = Table(
        alert_data,
        colWidths=[90, 280, 100]
    )

    alert_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.darkred),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ])
    )

    content.append(alert_table)
    content.append(Spacer(1, 20))


    recommendations = []

    if critical_cves > 5:
        recommendations.append(
            "Patch critical vulnerabilities immediately."
        )

    if malware_count > 10:
        recommendations.append(
            "Investigate malware detections."
        )

    if phishing_count > 0:
        recommendations.append(
            "Conduct phishing awareness training."
        )

    if attack_chains > 0:
        recommendations.append(
            "Review correlated attack chains."
        )

    content.append(PageBreak())

    content.append(
        Paragraph(
            "Recommendations",
            styles["Heading1"]
        )
    )

    for rec in recommendations:
        content.append(
            Paragraph(
                f"• {rec}",
                styles["Normal"]
            )
        )

    doc.build(content)

    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition":
            "attachment; filename=sentinelai-executive-report.pdf"
        }
    )